
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnhgazjslqtndfyphkut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaGdhempzbHF0bmRmeXBoa3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NzIwMTAsImV4cCI6MjA1NjM0ODAxMH0.6Be49vSzGyewrw8En4K5xP9YmJRVrO36NmK0JIn_t2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type helper for string literal types to avoid excessive instantiation errors
export type FromStringLiteral<T extends string> = T extends `${infer U}` ? U : never;
