
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqcjdavlrhuthzheqtwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xY2pkYXZscmh1dGh6aGVxdHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTU0NzcsImV4cCI6MjA1NjY3MTQ3N30.WnHsiGQ4D9qmD_kK0IvvD31XgwfNXBnYOguGZ-ak9Mw";

// Define extended Database type to match our actual database structure
type ExtendedDatabase = Database & {
  public: {
    Tables: {
      courses: {
        Row: {
          id: string;
          title: string;
          description: string;
          level: string;
          category: string;
          duration: number;
          prerequisites: string[];
          author: string;
          author_role: string | null;
          image_url: string | null;
          published: boolean | null;
          slug: string;
          popularity: number | null;
          rating: number | null;
          review_count: number | null;
          tags: string[] | null;
          price: number | null;
          discount: number | null;
          featured: boolean | null;
          language: string | null;
          certificate_available: boolean | null;
          updated_at: string | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      modules: {
        Row: {
          id: string;
          course_id: string;
          title: string;
          description: string | null;
          order_index: number;
          duration: number | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      lessons: {
        Row: {
          id: string;
          module_id: string;
          title: string;
          content: string;
          duration: number;
          video_url: string | null;
          order_index: number;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      exercises: {
        Row: {
          id: string;
          lesson_id: string;
          title: string;
          description: string;
          difficulty: string;
          code_template: string | null;
          solution: string | null;
          hints: string[] | null;
          points: number | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      test_cases: {
        Row: {
          id: string;
          exercise_id: string;
          input: string;
          expected_output: string;
          is_public: boolean | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      resources: {
        Row: {
          id: string;
          lesson_id: string;
          title: string;
          type: string;
          url: string;
          description: string | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      quizzes: {
        Row: {
          id: string;
          lesson_id: string;
          question: string;
          options: any;
          correct_answer: number;
          explanation: string | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          course_id: string;
          completed_lessons: string[];
          completed_exercises: string[];
          current_lesson: string | null;
          started_at: string | null;
          last_accessed_at: string | null;
          completion_percentage: number | null;
          quiz_scores: Record<string, number> | null;
          certificate_issued: boolean | null;
          notes: Record<string, string> | null;
          bookmarks: string[] | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      achievements: {
        Row: {
          id: string;
          title: string;
          description: string;
          icon: string;
          condition: string;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      user_achievements: {
        Row: {
          id: string;
          user_id: string;
          achievement_id: string;
          progress: number | null;
          is_unlocked: boolean | null;
          unlocked_at: string | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
      user_portfolio_progress: {
        Row: {
          id: string;
          user_id: string;
          current_level: number | null;
          unlocked_years: string[] | null;
          quiz_history: any | null;
          achievements: string[] | null;
          last_updated: string | null;
          created_at: string | null;
        };
        Insert: any;
        Update: any;
      };
    };
  };
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
